// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  Auth: {
    identityPoolId: 'us-east-1:77e4819a-8ed7-44a5-9b7b-56fce7b837e8',
    region: 'us-east-1',
    userPoolId: 'us-east-1_B5uvdhugj',
    userPoolWebClientId: '6ap18ckmq0b4vl61doglraekqg',
    mandatorySignIn: false,
    oauth: {
      domain: 'auth.lucunas.io',
      scope: [
        'phone',
        'email',
        'profile',
        'openid',
        'aws.cognito.signin.user.admin'
      ],
      redirectSignIn: 'https://lucunas.io',
      redirectSignOut: 'https://lucunas.io',
      responseType: 'code',
      options: {
        AdvancedSecurityDataCollectionFlag: true
      }
    }
  }
};


export default awsmobile;
